version: '3.8'

services:
  # 1. PostgreSQL Database Container
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: fraud_detection_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # 🔍 Checks every 3s if PostgreSQL is actually accepting database queries
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fraud_detection_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # 2. Spring Boot Middleware Container
  springboot_app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/fraud_detection_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    # ⏳ Tells Spring Boot to wait until PostgreSQL passes its healthcheck
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
